# Automatically scale the application Pods based on CPU usage
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: aws-eks-platform-hpa
  namespace: aws-eks-platform

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aws-eks-platform-app

  minReplicas: 2
  maxReplicas: 6

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60